# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170307_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
