# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comments_comments_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
